### ISSUE TITLE
Game crashes when dropping a lot of items

### ISSUE THREAD

**Issue by Berkouli** [Sydokiddo/auditory#3]
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 6/24/22, 1:45 PM
Description: Accessing LegacyRandomSource from multiple threads

java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.2)
	at net.minecraft.util.thread.LockHelper.crash(LockHelper:84)
	at net.minecraft.util.math.random.CheckedRandom.next(CheckedRandom:49)
	at net.minecraft.util.math.random.BaseRandom.nextDouble(BaseRandom:62)
	at net.minecraft.util.math.random.GaussianGenerator.next(GaussianGenerator:34)
	at net.minecraft.util.math.random.CheckedRandom.nextGaussian(CheckedRandom:57)
	at net.minecraft.client.world.ClientWorld.handler$dnp000$randomBlockDisplayTick(ClientWorld:4134)
	at net.minecraft.client.world.ClientWorld.randomBlockDisplayTick(ClientWorld:403)
	at net.minecraft.client.world.ClientWorld.doRandomBlockDisplayTicks(ClientWorld:358)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1854)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1101)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:734)
	at net.minecraft.client.main.Main.main(Main:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Fioofyy** [comment]
This also happened to me but when bow spamming.

**Comment by Sydokiddo** [comment]
Fixed both the item dropping crash and the bow spamming crash in the next release!
